spring:
  application:
    name: book-shop

  datasource:
    url: jdbc:postgresql://localhost:5433/bookshop
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=24h

  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        "[enable.idempotence]": true
        "[max.in.flight.requests.per.connection]": 5
    consumer:
      group-id: book-shop-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.trusted.packages]": "*"

currency:
  api:
    url: https://cbr.ru/scripts/XML_daily.asp

logging:
  level:
    "[com.globus.book_shop]": DEBUG